sudo: required
services:
  - docker

before_install:
  - docker build -t ranuon98/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true ranuon98/docker-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-test"
  env: "Docker-test-env"
  bucket_name: "elasticbeanstalk-eu-central-1-565884025670"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"